POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Creating a Blog List App With Node $ Express",
  "author": "Omar Alktan <3",
  "url": "https://github.com/OmarAlkttan",
  "likes": 100
}